#!/bin/bash
# Forked  respin respun forked stolen and modified by DasGeek
# Tested w/ Elementary OS Loki & Ubuntu 17 and 18.04 LTS 
# Forked and spooned from some forum post I can no longer find in a galaxy of the internet
# Thank you to BigDaddyLinux and Skrappjaw for contributing!
# Version 1.3.1

	sudo apt-get install dialog
	cmd=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
	options=(
		$ "Install Flatpak Repository" off
		$# "Install Snaps Repository" off
	    9 "Ubuntu Restricted Extras" off
	    22 "Steam (Valve)" off
		25 "Lutris" off
		32 "Gnome Twitch Client" off
		34 "Discord (Snap)" off
		43 "Pycharm Pro (Pycharm Tools SNAP)" off
		44 "Mumble Client (SNAP)" off
		46 "DOSBox-X (SNAP)" off
		47 "ScummVM (SNAP)" off
		50 "Post Install Auto Clean Up & Update" off)

		choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
		clear
		for choice in $choices
		do
		    case $choice in
	        $)	
				#Install Flatpak Repository
				echo "Installing Flatpak Repository"
				sudo apt install flatpak -y
				;;

			$#)	
				#Install Snap Repository
				echo "Installing Snap Repository"
				sudo apt install snapd -y
				;;


			9)
				#Ubuntu Restricted Extras
				echo "Installing Ubuntu Restricted Extras"
				apt install ubuntu-restricted-extras -y
				;;

			22)	#Steam
				echo "Installing Steam"				
				apt install steam -y
				;;
			25)	#Lutris
				echo "Installing Lutris"
				ver=$(lsb_release -sr); if [ $ver != "17.10" -a $ver != "17.04" -a $ver != "16.04" ]; then ver=16.04; fi
				echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
				wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add -
				sudo apt-get update
				sudo apt-get install lutris -y
				;;
			32) #Gnome Twitch Client
				echo "installing Gnome Twitch"
				apt install gnome-twitch -y
				;;
					
			34)
				#Discord
				sudo apt install snapd
				sudo snap install discord
				;;
			44) #Mumble Client (SNAP)
				echo "Mumble"
				apt install snapd
				snap install mumble		
				;;
				

			46) #DOSBox-X (SNAP)
				echo "Installing DOSBox-X"
				apt install snapd
				snap install dosbox-x
				;;
			
			47) #ScummVM (SNAP)
				echo "Installing ScummVM"
				apt install snapd
				snap install scummvm
				;;

			50)  #Clean up
				echo "Running Clean Up And Update"
				sudo apt update
				sudo apt upgrade
				sudo apt-get autoremove
				;;


	    esac
	done


