#!/bin/bash
# Forked  respin respun forked stolen and modified by DasGeek
# Tested w/ Elementary OS Loki & Ubuntu 17 and 18.04 LTS 
# Forked and spooned from some forum post I can no longer find in a galaxy of the internet
# Thank you to BigDaddyLinux and Skrappjaw for contributing!
# Version 1.3.1

	sudo apt-get install dialog
	cmd=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
	options=(
		$ "Install Flatpak Repository" off
		$# "Install Snaps Repository" off
		1 "Sublime Text" off    # any option can be set to default to "on"
	    2 "Simplenote (SNAP)" off
	    3 "Gedit" off
	    4 "Terminator" off
	    5 "Filezilla" off
	    8 "Elementary Tweaks" off
	    9 "Ubuntu Restricted Extras" off
	    11 "Gnome Tweak Tool" off
	    18 "Visual Studio Code" off
		19 "Virtualbox" off
		20 "Atom" off
		21 "Putty" off
		26 "Hexchat" off
		36 "Etcher" off
 /etc/apt/sources.list.d/enpass.list		37 "Tilix" off
		38 "Synology NAS Backup" off
		40 "Catfish - File Search" off
		41 "Xfce Monitor Move Script" off
		42 "Signal" off
		43 "Pycharm Pro (Pycharm Tools SNAP)" off
		48 "get-iplayer (SNAP)" off
		49 "Enpass" off



		50 "Post Install Auto Clean Up & Update" off)

		choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
		clear
		for choice in $choices
		do
		    case $choice in
	        $)	
				#Install Flatpak Repository
				echo "Installing Flatpak Repository"
				sudo apt install flatpak -y
				;;

			$#)	
				#Install Snap Repository
				echo "Installing Snap Repository"
				sudo apt install snapd -y
				;;




			1)
	            #Install Sublime Text*
				echo "Installing Sublime Text"
				wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
				sudo apt-get install apt-transport-https
				echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
				sudo apt update
				sudo apt install sublime-text -y
				;;

			2)
			    #Simplenote (SNAP)
				echo "Installing Simplenote"
				apt install snapd
				snap install simplenote
				;;


	            
    			
    		3)	
				#Install Gedit
				echo "Gedit"
				apt install gedit -y
				;;
				
			4)
				#Terminator
				echo "Installing Skynet/Terminator"
				apt install terminator -y
				;;

			5)
				#Filezilla
				echo "Filezilla not related to Godzilla"
				apt install filezilla -y
				;;
			
			8)
				#Elementary OS Tweaks
				echo "Installing Elementary Tweaks"
				sudo apt-get install software-properties-common
				sudo apt-get update
				sudo apt-get install elementary-tweaks -y
				;;

			9)
				#Ubuntu Restricted Extras
				echo "Installing Ubuntu Restricted Extras"
				apt install ubuntu-restricted-extras -y
				;;

			11)
				#Gnome tweak tool
				echo "Installing Gnome Tweak Tool"
				apt install gnome-tweak-tool -y
				;;


			18)
				#Visual Studio Code
				echo "Visual Studio Code"
				wget -O visualstudio.deb https://go.microsoft.com/fwlink/?LinkID=760868
				dpkg -i visualstudio.deb
				;;

			19)	#Virtualbox
				echo "Installing Virtualbox"
				sudo apt install virtualbox -y
				;;

			20)	#Atom
				echo "Installing Atom"				
				cd ~/Downloads			
				wget -O atom-amd64.deb https://atom.io/download/deb			
				dpkg -i atom-amd64.deb
				apt-get install -f -y
				rm -rf atom-amd64.deb
				apm install atom-html-preview
				;;

			21)	#Putty
				echo "Putty"
				apt install putty -y
				;;

			26)	#Hexchat
				echo "Installing Hexchat"
				apt install hexchat -y
				;;

			31) #Pithos
				echo "installing Pithos"
				apt install pithos -y
				;;
		
			33) #Gnome-do
				echo "Installing GnomeDo"
				apt install gnome-do -y
				apt install gnome-do-plugins -y
				;;

			36) #Etcher ISO Creator
				echo "Installing Etcher"
				cd ~/Downloads
				wget -O etcher.zip https://github.com/resin-io/etcher/releases/download/v1.4.4/etcher-electron-1.4.4-linux-x64.zip
				sudo apt install unzip -y
				unzip etcher*.zip
				chmod +x ~/Downloads/etcher-*.AppImage
				;;

			37) #Tilix (Tiling Terminal)
				echo "Installing Tilix"
				apt install tilix -y
				;;

			38) #Synology NAS Assistant & Backup
				echo "Installing Syn Assist, CloudStation Backup"
				wget -O synassistant.deb https://global.download.synology.com/download/Tools/Assistant/6.1-15163/Ubuntu/x86_64/synology-assistant_6.1-15163_amd64.deb
				sudo dpkg -i synassistant*.deb
				apt-get install -f -y
				rm -rf synassistant*.deb
				wget -O cloudback.deb https://global.download.synology.com/download/Tools/CloudStationBackup/4.2.6-4408/Ubuntu/Installer/x86_64/synology-cloud-station-backup-4408.x86_64.deb
				sudo dpkg -i cloudback*.deb
				apt-get install -f -y
				rm -rf cloudback*.deb
				;;
			
			40) #Install Catfish
					echo "Installing Catfish"
					sudo apt install catfish -y
					;;

			41) #Install monitor move window script Xfce
					echo "Monitor move window script"
					wget https://raw.githubusercontent.com/dasgeekchannel/move-to-next-monitor/master/move-to-next-monitor
					cd ~/Documents
					currentuser=$(who | awk 'NR==1{print $1}')
					chmod +x ~/Documents/move-to-next-monitor
		    		chown -R $currentuser:$currentuser ~/Documents/move-to-next-monitor
					;;

			42) #Signal
					echo "Installing Signal Messenger"
					sudo apt-get install curl -y
					curl -s https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -				
         			echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
    				sudo apt update && sudo apt install signal-desktop -y
    				;;
			43) #Python Tools (Dev Testing)
					echo "Installing Python Tools"
					#Install PIP
					sudo apt-get install -y python3-pip
					#Install packages and dev tools
					sudo apt-get install build-essential libssl-dev libffi-dev python-dev -y
					#Pycharm 
					apt install openjdk-8-jdk -y
					apt install python3-setuptools -y
					#Install SNAP
					sudo apt install snapd -y
					sudo snap install pycharm-professional
					;;

				
			48) #get-iplayer (SNAP)
				echo "get-iplayer"
				apt install snapd
				snap install get-iplayer
				;;
				
			49) #Enpass
				sudo echo "deb http://repo.sinew.in/ stable main" > \ /etc/apt/sources.list.d/enpass.list				
				wget -O - https://dl.sinew.in/keys/enpass-linux.key | apt-key add -
				sudo apt update && sudo apt install enpass -y
				;;

					
			50)  #Clean up
				echo "Running Clean Up And Update"
				sudo apt update
				sudo apt upgrade
				sudo apt-get autoremove
				;;


	    esac
	done

	echo
	echo
	echo "Choose from the following categories:"
	echo
	echo "	1 - Multimedia"
	echo "	2 - Internet"
	echo "	3 - Gaming"
	echo "	4 - Tools and Tweaks"
	echo "	0 - Exit"
	echo "Enter the number for the category and press [Enter]"

	read menu

	if [ $menu = "1" ]; then /bin/bash categories/multimedia
		elif [ $menu = "2" ] ; then /bin/bash categories/internet
		elif [ $menu = "3" ] ; then /bin/bash categories/gaming
		elif [ $menu = "4" ] ; then /bin/bash categories/tools
		elif [ $menu = "0" ] ; then exit
		else echo "Sorry, that was not a valid selection"
	fi
